@startuml
start
if (Workingday) then (yes)
if (10bis Credit > 0) then (yes)
  :Purchase Shufersal\nCoupon;
else (no)
endif
else (no)
endif

: Generate report with coupons\n barcodes;
: Save report as PDF and HTML ;
: Publish PDF to WhatsApp group;
stop
@enduml
