@startuml
start

: Read commands from WhatsApp;
if (/disable command exists) then (yes)
else
    if (Workingday & credit > 0) then (yes)
      :Purchase Shufersal\n Coupon;
    else (no)
    endif
endif


: Generate report with coupons\n barcodes;
: Save report as PDF and HTML ;
: Publish PDF to WhatsApp group;
stop
@enduml
