name: Process PlantUML

on: [push, pull_request]

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: compile markdown source
        uses: kfiry77/mdcompile@v1.0.0
        with:
          output_dir: "mdcompile_files"

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add updated diagrams"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
