name: Process PlantUML

on: [push, pull_request]

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: compile markdown source
        uses: kfiry77/mdcompile@v1.0.0
        with:
          output_dir: "mdcompile_files"
          
